# Generated by Django 3.1.7 on 2021-05-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unknownvisitor',
            name='contact',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='unknownvisitor',
            name='visiting',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
