# Generated by Django 3.1.7 on 2021-05-12 06:14

from django.db import migrations, models
import people.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20210512_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=people.models.upload_location),
        ),
    ]
